---
## Homework 10 - QR Factorization 
---


### Problem 1:  

**PART A:** Fill in the function given below to find the QR factorization of a matrix $A$.


In [4]:
import numpy as np

def qr(A):
    # This function takes a single input: a matrix A stored as a 2-d numpy array.
    # Your function can assume that A has independent columns.
    
    # qr(A) should return a pair of matrices (Q, R) such that:
    # If A is NxK, Q is NxK and R is KxK
    # Q is orthogonal
    # R is upper triangular
    # Q*R = A
    

    n, m = A.shape # get the shape of A

    Q = np.empty((n, n)) # initialize matrix Q
    u = np.empty((n, n)) # initialize matrix u

    u[:, 0] = A[:, 0]
    Q[:, 0] = u[:, 0] / np.linalg.norm(u[:, 0])

    for i in range(1, n):

        u[:, i] = A[:, i]
        for j in range(i):
            u[:, i] -= (A[:, i] @ Q[:, j]) * Q[:, j] # get each u vector

        Q[:, i] = u[:, i] / np.linalg.norm(u[:, i]) # compute each e vetor

    R = np.zeros((n, m))
    for i in range(n):
        for j in range(i, m):
            R[i, j] = A[:, j] @ Q[:, i]

    
    return (Q, R)
#Code from https://python.quantecon.org/qr_decomp.html

**PART B:** Test your function from **1(A)** on the following matrix:

$$ A = \begin{bmatrix} 0 & 1 & 2 \\ 1 & 0 & 1 \\ 1 & 1 & 0 \end{bmatrix} $$

Note that we found the $QR$ decomposition of this particular matrix by hand in HW9, so you can check your output.

In [5]:
# Call function using matrix A
A=np.array([[0,1,2],[1,0,1],[1,1,0]])
Q,R=qr(A)
print('Q =',Q)
print('R =', R)

Q = [[ 0.          0.81649658  0.57735027]
 [ 0.70710678 -0.40824829  0.57735027]
 [ 0.70710678  0.40824829 -0.57735027]]
R = [[1.41421356 0.70710678 0.70710678]
 [0.         1.22474487 1.22474487]
 [0.         0.         1.73205081]]


### Problem 2:  

**PART A:** Fill in the function given below to use the back substitution algorithm.

In [6]:
import numpy as np
def back_substitute(R, b):
    """This function takes two inputs:
    + Matrix R stored as a 2-d numpy array.  Your function can assume that R is upper-triangular with nonzero diagonal.
    + Vector b stored as a 1-d numpy vector.

    This function should return a vector x such that R * x = b.

    Don't use a numpy solve function for this.
    Follow the textbook algorithm 11.1 "Back substitution".
    """
    x=[]
    for k in range(len(b)):
        x.append(0)
    for i in range(len(b)-1,-1,-1):
        temp=b[i]
        for j in range(len(b)-1,i,-1):
            temp -=(x[j]*R[i,j])
        x[i] = temp/R[i,i]
    return x

In [7]:
R=np.array([[1,1,2],[0,1,1],[0,0,3]])
b = [0,0,3]
print(back_substitute(R,b))

[-1.0, -1.0, 1.0]


**PART B:** Test your function from **2(A)** on the following linear system:

$$ \begin{bmatrix} 1 & 1 & 2 \\ 0 & 1 & 1 \\ 0 & 0 & 3 \end{bmatrix}\textbf{x} = \begin{bmatrix} 0 \\ 0 \\ 3 \end{bmatrix} $$

### Problem 3:  

**PART A:** Fill in the function given below to use the solving linear equations via QR factorization algorithm.

In [31]:
import numpy as np
def solve(A, b):
    """This function takes two inputs:
    + Matrix A stored as a 2-d numpy array.  Your function can assume that A has independent columns.
    + Vector b stored as a 1-d numpy vector.

    This function should return a vector x such that A * x = b.

    You MUST use your qr() and back_substitute() functions to solve this linear system.
    Follow the textbook algorithm 11.2 "Solving linear equations via QR factorization".
    """
    Q, R=qr(A)
    QT = np.transpose(Q)
    QTB = np.dot(QT,b)
    x=back_substitute(R,QTB)
    return x

**PART B:** Test your function from **3(A)** on the following linear system:

$$ \begin{bmatrix} 0 & 1 & 2 \\ 1 & 0 & 1 \\ 1 & 1 & 0 \end{bmatrix}\textbf{x} = \begin{bmatrix} 0 \\ 0 \\ 3 \end{bmatrix} $$



In [32]:
A = np.array([[0,1,2], [1,0,1], [1,1,0]])
b = [0,0,3]
print(solve(A,b))

[1.0000000000000002, 2.0000000000000004, -1.0000000000000004]
